### ISSUE TITLE
Debugbar disapper if session panel is active

### ISSUE THREAD

**Issue by martinsifra** [fprochazka/Nette-Session-DebugBar#19]
Don't what it can be, but with Nette 2.2 and 2.3 if I activate session panel debuggbar is not generated and append to response. I hope that everithing is configurated normally.

**Comment by enumag** [comment]
It works fine for me.

**Comment by martinsifra** [comment]
And don't you know what could affect it? I've tried everithing - cleaning temp, clean Nette and without success.

**Comment by enumag** [comment]
Unfortunately I don't know.

**Comment by martinsifra** [comment]
Today I tried to add session panel to latest clean nette-sandbox and debugbar is still not generated and append to page.

**Comment by enumag** [comment]
I tried it as well on clean sandbox and it works fine for me.
