### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by mabar** [fprochazka/Nette-Session-DebugBar#22]
Please add text "session" to the icon. Icon is not much descriptive.

**Comment by enumag** [comment]
I agree that the icon is bad but I won't add the text. The debug bar should only contain important things - icons to open the tools and some important numbers. Most certainly not a useless word. But if you have a better icon with useful license feel free to send a PR.

**Comment by mabar** [comment]
So please only add top: 2px on <img>, icon is out of bar. (Tracy 2.4.5)

**Comment by enumag** [comment]
This project it not really maintained but you can send a pull request I guess. I might fix it later myself but that'll likely take a while.
